repos:
  - repo: local
    hooks:
      # ruff (check + format)
      - id: ruff
        name: ruff
        entry: poetry run ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format
        language: system
        types: [python]
      # mypy
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
      # clang-tidy
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy -p instrumentation/build/ --quiet --fix
        language: system
        files: \.(c|h|cc|cpp|hpp)$
        exclude: ^instrumentation/build/
      # clang-format
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(c|h|cc|cpp|hpp)$
        exclude: ^instrumentation/build/
