version: '3.8'

services:
  fuzztastic-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: fuzztastic-dev
    image: fuzztastic-dev:latest
    container_name: fuzztastic-dev
    volumes:
      - .:/fuzztastic:cached
    restart: unless-stopped
    ports:
      - "8051:8050"

  fuzztastic:
    build:
      context: .
      dockerfile: Dockerfile
      target: fuzztastic
    image: fuzztastic:latest
    container_name: fuzztastic
    volumes:
      - ./data/demo:/fuzztastic/data/demo
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "8050:8050"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
