version: '3.8'

services:
  fuzztastic-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: fuzztastic-dev
    image: fuzztastic-dev:latest
    container_name: fuzztastic-dev
    volumes:
      - .:/fuzztastic:cached
    restart: unless-stopped

  fuzztastic:
    build:
      context: .
      dockerfile: Dockerfile
      target: fuzztastic
    image: fuzztastic:latest
    container_name: fuzztastic
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
